name: CI
on: [push, pull_request]
jobs:
  pylama:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with: {python-version: '3.9'}
    - name: Install dependencies
      run: pip install tox
    - name: Run pylama
      run: tox -e pylama
  mypy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with: {python-version: '3.9'}
    - name: Install dependencies
      run: pip install tox
    - name: Run mypy
      run: tox -e mypy
